sonar.projectKey=devgm10_landing-page
sonar.organization=devgm10

# Routes to analyze
sonar.sources=src

# Routes to exclude from the analysis
sonar.coverage.exclusions=**/*.vue,**/*.config.js,**/*.data.js,**/main.js,**/router/**,**/locales/**,**/composables/**,**/services/**,**/utils/**,**/validators/**

# Source code coding
sonar.sourceEncoding=UTF-8